"""MATS Rationalization Detection - Arcuschin Replication & ICRL Sycophancy."""

from .data_generation import (
    Domain,
    LOCATION_PAIRS,
    DATE_PAIRS,
    POPULATION_PAIRS,
    generate_question_pairs,
    generate_geography_pairs,
    generate_date_pairs,
    generate_population_pairs,
    generate_all_pairs,
    format_chat_prompt,
    get_system_prompt,
    SYSTEM_PROMPTS,
)
from .labeling import (
    Classification,
    extract_yes_no,
    detect_contradiction,
    label_trajectory,
    calculate_contradiction_rate,
    format_for_csv,
)
from .sycophancy import (
    QuestionCategory,
    FactualQuestion,
    SycophancyLabel,
    TrajectoryResult,
    SYSTEM_PROMPT as SYCOPHANCY_SYSTEM_PROMPT,
    POSITIVE_FEEDBACK_TEMPLATES,
    NEGATIVE_FEEDBACK_TEMPLATES,
    STRONG_NEGATIVE_FEEDBACK_TEMPLATES,
    CAPITAL_QUESTIONS,
    SCIENCE_QUESTIONS,
    GEOGRAPHY_QUESTIONS,
    get_all_questions,
    get_questions_by_category,
    get_feedback,
    extract_answer,
    check_answer,
    label_trajectory as label_sycophancy_trajectory,
)

__all__ = [
    # Data generation
    "Domain",
    "LOCATION_PAIRS",
    "DATE_PAIRS",
    "POPULATION_PAIRS",
    "generate_question_pairs",
    "generate_geography_pairs",
    "generate_date_pairs",
    "generate_population_pairs",
    "generate_all_pairs",
    "format_chat_prompt",
    "get_system_prompt",
    "SYSTEM_PROMPTS",
    # Labeling
    "Classification",
    "extract_yes_no",
    "detect_contradiction",
    "label_trajectory",
    "calculate_contradiction_rate",
    "format_for_csv",
    # Sycophancy
    "QuestionCategory",
    "FactualQuestion",
    "SycophancyLabel",
    "TrajectoryResult",
    "SYCOPHANCY_SYSTEM_PROMPT",
    "POSITIVE_FEEDBACK_TEMPLATES",
    "NEGATIVE_FEEDBACK_TEMPLATES",
    "STRONG_NEGATIVE_FEEDBACK_TEMPLATES",
    "CAPITAL_QUESTIONS",
    "SCIENCE_QUESTIONS",
    "GEOGRAPHY_QUESTIONS",
    "get_all_questions",
    "get_questions_by_category",
    "get_feedback",
    "extract_answer",
    "check_answer",
    "label_sycophancy_trajectory",
]
